#!/bin/sh
echo 
echo compiling...
echo 
g++ wind-thermo.cpp -o wind-thermo
echo 
echo running...
echo 
./wind-thermo 10

echo Do you want to keep the renders ? [Y/n]  
read rep

if [ $rep == "N" or "n" ]:
then
	rm renders/*.png
else:
	echo "ok !"
fi
